// Generated by gencpp from file nlink_parser/IotFrame0.msg
// DO NOT EDIT!


#ifndef NLINK_PARSER_MESSAGE_IOTFRAME0_H
#define NLINK_PARSER_MESSAGE_IOTFRAME0_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <nlink_parser/IotFrame0Node.h>

namespace nlink_parser
{
template <class ContainerAllocator>
struct IotFrame0_
{
  typedef IotFrame0_<ContainerAllocator> Type;

  IotFrame0_()
    : uid(0)
    , system_time(0)
    , io_status(0)
    , nodes()  {
    }
  IotFrame0_(const ContainerAllocator& _alloc)
    : uid(0)
    , system_time(0)
    , io_status(0)
    , nodes(_alloc)  {
  (void)_alloc;
    }



   typedef uint32_t _uid_type;
  _uid_type uid;

   typedef uint32_t _system_time_type;
  _system_time_type system_time;

   typedef uint8_t _io_status_type;
  _io_status_type io_status;

   typedef std::vector< ::nlink_parser::IotFrame0Node_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::nlink_parser::IotFrame0Node_<ContainerAllocator> >> _nodes_type;
  _nodes_type nodes;





  typedef boost::shared_ptr< ::nlink_parser::IotFrame0_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nlink_parser::IotFrame0_<ContainerAllocator> const> ConstPtr;

}; // struct IotFrame0_

typedef ::nlink_parser::IotFrame0_<std::allocator<void> > IotFrame0;

typedef boost::shared_ptr< ::nlink_parser::IotFrame0 > IotFrame0Ptr;
typedef boost::shared_ptr< ::nlink_parser::IotFrame0 const> IotFrame0ConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nlink_parser::IotFrame0_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nlink_parser::IotFrame0_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::nlink_parser::IotFrame0_<ContainerAllocator1> & lhs, const ::nlink_parser::IotFrame0_<ContainerAllocator2> & rhs)
{
  return lhs.uid == rhs.uid &&
    lhs.system_time == rhs.system_time &&
    lhs.io_status == rhs.io_status &&
    lhs.nodes == rhs.nodes;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::nlink_parser::IotFrame0_<ContainerAllocator1> & lhs, const ::nlink_parser::IotFrame0_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace nlink_parser

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::nlink_parser::IotFrame0_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nlink_parser::IotFrame0_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nlink_parser::IotFrame0_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nlink_parser::IotFrame0_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nlink_parser::IotFrame0_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nlink_parser::IotFrame0_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nlink_parser::IotFrame0_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8854697b4ab999e932111a65ada95ab0";
  }

  static const char* value(const ::nlink_parser::IotFrame0_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8854697b4ab999e9ULL;
  static const uint64_t static_value2 = 0x32111a65ada95ab0ULL;
};

template<class ContainerAllocator>
struct DataType< ::nlink_parser::IotFrame0_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nlink_parser/IotFrame0";
  }

  static const char* value(const ::nlink_parser::IotFrame0_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nlink_parser::IotFrame0_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 uid\n"
"uint32 system_time\n"
"uint8 io_status\n"
"IotFrame0Node[] nodes\n"
"\n"
"================================================================================\n"
"MSG: nlink_parser/IotFrame0Node\n"
"uint32 uid\n"
"float32 dis\n"
"float32 aoa_angle_horizontal\n"
"float32 aoa_angle_vertical\n"
"float32 fp_rssi\n"
"float32 rx_rssi\n"
"string user_data\n"
;
  }

  static const char* value(const ::nlink_parser::IotFrame0_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nlink_parser::IotFrame0_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.uid);
      stream.next(m.system_time);
      stream.next(m.io_status);
      stream.next(m.nodes);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct IotFrame0_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nlink_parser::IotFrame0_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nlink_parser::IotFrame0_<ContainerAllocator>& v)
  {
    s << indent << "uid: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.uid);
    s << indent << "system_time: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.system_time);
    s << indent << "io_status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.io_status);
    s << indent << "nodes[]" << std::endl;
    for (size_t i = 0; i < v.nodes.size(); ++i)
    {
      s << indent << "  nodes[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::nlink_parser::IotFrame0Node_<ContainerAllocator> >::stream(s, indent + "    ", v.nodes[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // NLINK_PARSER_MESSAGE_IOTFRAME0_H
