// Generated by gencpp from file nlink_parser/LinktrackNode4Tag.msg
// DO NOT EDIT!


#ifndef NLINK_PARSER_MESSAGE_LINKTRACKNODE4TAG_H
#define NLINK_PARSER_MESSAGE_LINKTRACKNODE4TAG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <nlink_parser/LinktrackNode4Anchor.h>

namespace nlink_parser
{
template <class ContainerAllocator>
struct LinktrackNode4Tag_
{
  typedef LinktrackNode4Tag_<ContainerAllocator> Type;

  LinktrackNode4Tag_()
    : id(0)
    , voltage(0.0)
    , anchors()  {
    }
  LinktrackNode4Tag_(const ContainerAllocator& _alloc)
    : id(0)
    , voltage(0.0)
    , anchors(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _id_type;
  _id_type id;

   typedef float _voltage_type;
  _voltage_type voltage;

   typedef std::vector< ::nlink_parser::LinktrackNode4Anchor_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::nlink_parser::LinktrackNode4Anchor_<ContainerAllocator> >> _anchors_type;
  _anchors_type anchors;





  typedef boost::shared_ptr< ::nlink_parser::LinktrackNode4Tag_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nlink_parser::LinktrackNode4Tag_<ContainerAllocator> const> ConstPtr;

}; // struct LinktrackNode4Tag_

typedef ::nlink_parser::LinktrackNode4Tag_<std::allocator<void> > LinktrackNode4Tag;

typedef boost::shared_ptr< ::nlink_parser::LinktrackNode4Tag > LinktrackNode4TagPtr;
typedef boost::shared_ptr< ::nlink_parser::LinktrackNode4Tag const> LinktrackNode4TagConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nlink_parser::LinktrackNode4Tag_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nlink_parser::LinktrackNode4Tag_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::nlink_parser::LinktrackNode4Tag_<ContainerAllocator1> & lhs, const ::nlink_parser::LinktrackNode4Tag_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.voltage == rhs.voltage &&
    lhs.anchors == rhs.anchors;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::nlink_parser::LinktrackNode4Tag_<ContainerAllocator1> & lhs, const ::nlink_parser::LinktrackNode4Tag_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace nlink_parser

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::nlink_parser::LinktrackNode4Tag_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nlink_parser::LinktrackNode4Tag_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nlink_parser::LinktrackNode4Tag_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nlink_parser::LinktrackNode4Tag_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nlink_parser::LinktrackNode4Tag_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nlink_parser::LinktrackNode4Tag_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nlink_parser::LinktrackNode4Tag_<ContainerAllocator> >
{
  static const char* value()
  {
    return "52d7d856087ab9caa357ff4bd2e80950";
  }

  static const char* value(const ::nlink_parser::LinktrackNode4Tag_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x52d7d856087ab9caULL;
  static const uint64_t static_value2 = 0xa357ff4bd2e80950ULL;
};

template<class ContainerAllocator>
struct DataType< ::nlink_parser::LinktrackNode4Tag_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nlink_parser/LinktrackNode4Tag";
  }

  static const char* value(const ::nlink_parser::LinktrackNode4Tag_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nlink_parser::LinktrackNode4Tag_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 id\n"
"float32 voltage\n"
"LinktrackNode4Anchor[] anchors\n"
"\n"
"================================================================================\n"
"MSG: nlink_parser/LinktrackNode4Anchor\n"
"uint8 id\n"
"float32 dis\n"
;
  }

  static const char* value(const ::nlink_parser::LinktrackNode4Tag_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nlink_parser::LinktrackNode4Tag_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.voltage);
      stream.next(m.anchors);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LinktrackNode4Tag_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nlink_parser::LinktrackNode4Tag_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nlink_parser::LinktrackNode4Tag_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.id);
    s << indent << "voltage: ";
    Printer<float>::stream(s, indent + "  ", v.voltage);
    s << indent << "anchors[]" << std::endl;
    for (size_t i = 0; i < v.anchors.size(); ++i)
    {
      s << indent << "  anchors[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::nlink_parser::LinktrackNode4Anchor_<ContainerAllocator> >::stream(s, indent + "    ", v.anchors[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // NLINK_PARSER_MESSAGE_LINKTRACKNODE4TAG_H
