# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from nlink_parser/TofsenseMFrame0.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import nlink_parser.msg

class TofsenseMFrame0(genpy.Message):
  _md5sum = "8b49d724777a20439f181e513a9f9e83"
  _type = "nlink_parser/TofsenseMFrame0"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint8 id
uint32 system_time
uint8 pixel_count
TofsenseMFrame0Pixel[] pixels

================================================================================
MSG: nlink_parser/TofsenseMFrame0Pixel
float32 dis
uint8 dis_status
uint16 signal_strength
"""
  __slots__ = ['id','system_time','pixel_count','pixels']
  _slot_types = ['uint8','uint32','uint8','nlink_parser/TofsenseMFrame0Pixel[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       id,system_time,pixel_count,pixels

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(TofsenseMFrame0, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.id is None:
        self.id = 0
      if self.system_time is None:
        self.system_time = 0
      if self.pixel_count is None:
        self.pixel_count = 0
      if self.pixels is None:
        self.pixels = []
    else:
      self.id = 0
      self.system_time = 0
      self.pixel_count = 0
      self.pixels = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_BIB().pack(_x.id, _x.system_time, _x.pixel_count))
      length = len(self.pixels)
      buff.write(_struct_I.pack(length))
      for val1 in self.pixels:
        _x = val1
        buff.write(_get_struct_fBH().pack(_x.dis, _x.dis_status, _x.signal_strength))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.pixels is None:
        self.pixels = None
      end = 0
      _x = self
      start = end
      end += 6
      (_x.id, _x.system_time, _x.pixel_count,) = _get_struct_BIB().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.pixels = []
      for i in range(0, length):
        val1 = nlink_parser.msg.TofsenseMFrame0Pixel()
        _x = val1
        start = end
        end += 7
        (_x.dis, _x.dis_status, _x.signal_strength,) = _get_struct_fBH().unpack(str[start:end])
        self.pixels.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_BIB().pack(_x.id, _x.system_time, _x.pixel_count))
      length = len(self.pixels)
      buff.write(_struct_I.pack(length))
      for val1 in self.pixels:
        _x = val1
        buff.write(_get_struct_fBH().pack(_x.dis, _x.dis_status, _x.signal_strength))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.pixels is None:
        self.pixels = None
      end = 0
      _x = self
      start = end
      end += 6
      (_x.id, _x.system_time, _x.pixel_count,) = _get_struct_BIB().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.pixels = []
      for i in range(0, length):
        val1 = nlink_parser.msg.TofsenseMFrame0Pixel()
        _x = val1
        start = end
        end += 7
        (_x.dis, _x.dis_status, _x.signal_strength,) = _get_struct_fBH().unpack(str[start:end])
        self.pixels.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_BIB = None
def _get_struct_BIB():
    global _struct_BIB
    if _struct_BIB is None:
        _struct_BIB = struct.Struct("<BIB")
    return _struct_BIB
_struct_fBH = None
def _get_struct_fBH():
    global _struct_fBH
    if _struct_fBH is None:
        _struct_fBH = struct.Struct("<fBH")
    return _struct_fBH
